---
title: "In-Class_Ex04"
author: "Thng Yao Wen"
date: 2023-05-05
date-modified: "`r Sys.Date()`"
---

```{r}
pacman::p_load(rstatix, gt, patchwork, tidyverse)
```

```{r}
exam_data <- read_csv("data/Exam_data.csv")

```

## Plot

::: panel-tabset
## The plot

```{r}
#| echo: false
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() + #normal distribution
  stat_qq_line()
```

## The code chunk

```{r}
#| eval: false
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() + #normal distribution
  stat_qq_line()
```
:::

::: callout-note
We can see that the points deviate significantly from the straight diagonal line
:::

## Plot (patchwork)

::: panel-tabset
## The plot

```{r}
#| echo: false
qq <- ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() + #normal distribution
  stat_qq_line()

sw_t <- exam_data %>%
  shapiro_test(ENGLISH) %>%
  gt() #give a nice table

tmp <- tempfile(fileext = '.png')
gtsave(sw_t, tmp)
table_png <- png::readPNG(tmp,
                          native = TRUE)
qq + table_png
```

## The code chunk

```{r}
#| eval: false
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() + #normal distribution
  stat_qq_line()
```
:::

```{r}
set.seed(1234) #impt esp for variance statistics. to not change values everytime we run
```

\`\`\`\`{r} \#
